apiVersion: v1
kind: Service
metadata:
  name: mongodb-arbiter
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
    role: arbiter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-arbiter
  labels:
    app: mongodb
    role: arbiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      role: arbiter
  template:
    metadata:
      labels:
        app: mongodb
        role: arbiter
    spec:
      containers:
        - name: mongodb-arbiter
          image: bitnami/mongodb:latest
          env:
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: mongodb-arbiter
            - name: MONGODB_REPLICA_SET_MODE
              value: arbiter
            - name: MONGODB_INITIAL_PRIMARY_HOST
              value: mongodb-primary
            - name: MONGODB_INITIAL_PRIMARY_PORT_NUMBER
              value: "27017"
            - name: MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-mongo
                  key: password
            - name: MONGODB_REPLICA_SET_KEY
              value: replicasetkey123
