apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myserviceb
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: ecommerce.mohamedhossam.me
      http:
        paths:
          - path: /api/v1/products
            pathType: Prefix
            backend:
              service:
                name: products-srv
                port:
                  number: 4000
          - path: /api/v1/product
            pathType: Prefix
            backend:
              service:
                name: products-srv
                port:
                  number: 4000
          - path: /api/v1/images
            pathType: Prefix
            backend:
              service:
                name: imageremover-service
                port:
                  number: 8000
          - path: /api/v1/orders
            pathType: Prefix
            backend:
              service:
                name: orders-srv
                port:
                  number: 8081
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 8000
          - path: /api/v1/cart
            pathType: Prefix
            backend:
              service:
                name: cartwishlist-srv
                port:
                  number: 4001
          - path: /api/v1/wishlist
            pathType: Prefix
            backend:
              service:
                name: cartwishlist-srv
                port:
                  number: 4001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
