apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: ecommercemainreg.azurecr.io/products:1.0.3
          ports:
            - containerPort: 4000
          env:
            - name: JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: authsecret
                  key: JWT_SECRET
            - name: KAFKA_BROKER
              value: "kafka-srv:9092"
            - name: USER_CREATION_TOPIC
              value: "user-created"
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: products-client
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-client
                  key: password
            - name: MONGO_HOST
              value: "mongodb-primary"
          livenessProbe:
            httpGet:
              path: /health/
              port: 4000
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: azure-k8s
